### ISSUE TITLE
大佬，求更新😥

### ISSUE THREAD

**Issue by qsmmhn** [Alpiiine/gcg-plugin#5]

**Comment by Alpiiine** [comment]
新功能由于工作原因近期没有时间加。

**Comment by pareshgami** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
smallbeginner, @ji-xiao-mo, @zhichicao, @panyongxu, @709kyb, @LineToAnyWhere, @xwisen, @LinKenCong, @0xtulaoda, @ericting, @qiwihui, @lixiaoyu77, @strategist614, @a2uk1, @yuhai-yang, @uu-z, @wangluxu, @luckyharry888, @jianpanxia233, @daog1, @alexanderhawl, @rj03hou, @keepmovinglife, @lj92458, @IceTeaz, @pkuntik, @0x-leen, @HandsomeMan-LAX, @CustomGame-Peo, @playgood111, @L0kiii, @MatrixA, @thurendous, @Lamhoiyan, @sclongyang, @co-star, @jiajianfa, @LindenWang01, @yaoting10, @wtypty2, @Roshanyu, @ClockTwelve, @bryant824-kb, @tristan1027, @echo672, @gillbates, @XunWind, @DuYr, @pick7, @ZRory
